// Generated by CoffeeScript 1.6.3
(function() {
  var FileCert, NewCert, a, args, argv, async, c, cn, complain, fs, pem, posh, usage, _i, _len, _ref;

  pem = require('pem');

  async = require('async');

  fs = require('fs');

  posh = require('./index');

  usage = function() {
    process.stderr.write("Usage: genposh [options] [cert filename...]\n\nOptions:\n  --help, -h        Show this message and exit\n  --out, -o         Directory in which to output files             [default: \".\"]\n  --days, -d        Days of validity for the generated certificate [default: 365]\n  --service, -s     SRV-style service name for the POSH file       [default: \"_xmpp-server._tcp\"]\n  --maxcerts, -m    The maximum number of certs to output in the\n                    x5c field.  0 means all.                       [default: 0]\n  --commonname, -c  Create a new certificate, with this common name (multiple ok)");
    return process.exit(64);
  };

  complain = function(er) {
    console.log(er);
    return process.exit(1);
  };

  NewCert = (function() {
    function NewCert(cn) {
      this.cn = cn;
      this.days = 365;
      this.dir = '.';
    }

    NewCert.prototype.create = function(cb) {
      var _this = this;
      return pem.createCertificate({
        days: this.days,
        selfSigned: true,
        commonName: this.cn
      }, function(er, keys) {
        if (er) {
          return cb(er);
        }
        return async.parallel([
          function(cb) {
            return fs.writeFile("" + _this.dir + "/" + _this.cn + "-key.pem", keys.clientKey, cb);
          }, function(cb) {
            return fs.writeFile("" + _this.dir + "/" + _this.cn + ".pem", keys.certificate, cb);
          }
        ], function(er, results) {
          return cb(er, keys.certificate);
        });
      });
    };

    return NewCert;

  })();

  FileCert = (function() {
    function FileCert(fn) {
      this.fn = fn;
    }

    FileCert.prototype.create = function(cb) {
      return fs.readFile(this.fn, function(er, data) {
        return cb(er, er ? null : data.toString('utf8'));
      });
    };

    return FileCert;

  })();

  argv = {
    help: false,
    maxcerts: 0,
    service: '_xmpp-server._tcp',
    days: 365,
    out: '.',
    certs: []
  };

  args = process.argv.slice(2);

  while (args.length) {
    a = args.shift();
    switch (a) {
      case '-h':
      case '--help':
        usage();
        break;
      case '-o':
      case '--out':
        argv.out = args.shift() || usage();
        break;
      case '-d':
      case '--days':
        argv.days = parseInt(args.shift()) || usage();
        break;
      case '-s':
      case '--service':
        argv.service = args.shift() || usage();
        break;
      case '-m':
      case '--maxcerts':
        argv.maxcerts = parseInt(args.shift()) || usage();
        break;
      case '-c':
      case '--commonname':
        cn = args.shift() || usage();
        argv.certs.push(new NewCert(cn));
        break;
      default:
        argv.certs.push(new FileCert(a));
    }
  }

  _ref = argv.certs;
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    c = _ref[_i];
    if (!(c instanceof NewCert)) {
      continue;
    }
    c.days = argv.days;
    c.dir = argv.out;
  }

  async.map(argv.certs, function(c, cb) {
    return c.create(cb);
  }, function(er, certs) {
    if (er) {
      complain(er);
    }
    return posh.create(certs, argv.maxcerts, function(er, json) {
      if (er) {
        complain(er);
      }
      return posh.write(argv.out, argv.service, json, function(er) {
        if (er) {
          return complain(er);
        }
      });
    });
  });

}).call(this);
